#!/bin/bash
. cd_global_functions

clear_and_move_down


echo " ** Testing Network Compatibility ** " 
echo ""
sleep 1
ipinfo=$(ifconfig | grep $net_if -A2 | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}')
echo -n " .. Hardware Address: $mac" 
echo ""
echo -n " .. Ip Address: $ipinfo" 

echo
if [ -n "$mac" ] && [ -n "$ipinfo" ]; then
	echo " ...... Physical Test Passed"
else
	echo " ...... Network Card May Not Be Compatible.  A Kernel Update May Be Required." 
	ifconfig -a
fi
echo
echo Press Enter To Continue
read enter

	echo " ** Testing Web Service ** " 
	webResult=`$curlCommand "${web}Test" $curlEnd`
	if [ "$webResult" != "true" ]; then
		echo " ...... Could Not Contact Web Service.  Try The Following In A Web Browser: ${web}Test" 
		echo "$webResult" 	
	else
		echo " ...... Web Service Connection Passed" 
	fi

echo
echo Press Enter To Continue
read enter

echo
echo " ** Testing Hard Drive Compatibility ** " 
sleep 1
get_hard_drives

echo
echo
echo " ** All Tests Complete ** "
echo Press Enter To Reboot
read enter




