#!/bin/bash

. /bin/cd_global_functions

if [ "$cancel_test" = "true" ]; then
  while true; do
    result=$($curlAuth --data "computerId=$computer_id" "${web}CheckForCancelledTask" $curlEnd)
    if [ "$result" = "true" ]; then
      error "Task Has Been Cancelled"
    fi
    sleep 30
  done
fi

