#!/bin/bash

. /bin/cd_global_functions

computer_id=$1
reporter_type=$2

if [ "$reporter_type" = "partclone" ]; then
  while [ -f "/tmp/clone.progress" ]; do
    post=$(tail -n 1 /tmp/clone.progress)
    result=$($curlAuth --data "computerId=$computer_id&progress=$post&progressType=partclone" "${web}UpdateProgress" $curlEnd)        
    sleep 2
  done	
else
  while [ -f "/tmp/wim.progress" ]; do
    if [ "$reporter_type" = "wimup" ]; then
      post=$(cat /tmp/wim.progress | dos2unix | sed -e 's/    /\n/g' | sed -e 's/done)/)\n/g' | tail -n 1)
    else #wimdown
      post=$(cat /tmp/wim.progress | dos2unix | sed -e 's/done/\n/g' | tail -n 1)
    fi
	
    if [ -z "$post" ]; then
      post="Please Wait."
    fi
    result=$($curlAuth --data "computerId=$computer_id&progress=$post&progressType=wim" "${web}UpdateProgress" $curlEnd)        
    sleep 2
  done
fi

