#!/bin/bash

. /bin/cd_global_functions

clear_and_move_down
echo " ** Computer Registration ** "
echo

echo " ** System MAC Address: $mac ** "
echo

while [ "$isError" != "false" ]; do
	
	echo " ** Enter A Computer Name To Register ** "
	echo
	echo -n "Computer Name: "
	read name
	if [ -z "$name" ]; then 
		echo
		continue
	fi
	echo
		registerResult=$($curlAuth --data "name=$name&mac=$mac&imageId=3&imageProfileId=3" ${web}AddComputer $curlClose)
		if [ ! "$?" = "0" ]; then
			echo " ...... Could Not Register Computer: $registerResult"
		else
			if [ "$(parse_json "$registerResult" .IsValid)" = "true" ]; then
				echo " ...... Success"
				isError="false"
			else
				echo " ...... $(parse_json "$registerResult" .Message)"
				isError="true"
			fi
			echo
		fi
done

echo " ** Press Enter To Reboot ** "
read Enter;
reboot -f;

