#!/bin/bash

. /bin/cd_global_functions

computer_id=$1
reporter_type=$2
is_ondemand=$3

if [ "$is_ondemand" = "true" ]; then
  exit 
fi

if [ "$reporter_type" = "partclone" ]; then
  while [ -f "/tmp/clone.progress" ]; do
    post=$(tail -n 1 /tmp/clone.progress)
    result=$($curlAuth --data "computerId=$computer_id&progress=$post&progressType=partclone" "${web}UpdateProgress" $curlEnd)        
    sleep 2
  done	
else  # wimup or wimdown
  while [ -f "/tmp/wim.progress" ]; do
    post=$(cat /tmp/wim.progress | dos2unix | sed -e 's/done/\n/g' | tail -n 1)
      
    if [[ "$post" == *"scanned"* ]]; then
      post="Scanning Files."
    fi
	 
    if [ -z "$post" ]; then
      post="Please Wait."
    fi
    result=$($curlAuth --data "computerId=$computer_id&progress=$post&progressType=wim" "${web}UpdateProgress" $curlEnd)        
    sleep 2
  done
fi

