#!/bin/bash

. /usr/local/bin/osx_global_functions

  if [ "$image_direction" = "push" ]; then
    while [ -f "/tmp/osx.progress" ]; do
      post="$(tail -n 1 /tmp/osx.progress | cut -f2) %"
      result=$($curlAuth --data "computerId=$computer_id&progress=$post&progressType=wim" "${web}UpdateProgress" $curlEnd)        
      sleep 2
    done
  else
    while [ -f "/tmp/osx.progress" ]; do
      post=$(tail -n 1 /tmp/osx.progress)
      result=$($curlAuth --data "computerId=$computer_id&progress=$post&progressType=wim" "${web}UpdateProgress" $curlEnd)        
	  echo "$post" | grep -i "created" > /dev/null
	  if [ "$?" = "0" ]; then
	    echo "$post" >> $CLIENT_LOG
	  fi
      sleep 2
    done
  fi

 	


