#!/bin/bash

. /bin/cd_global_functions

if [ "$started_from_init" != "true" ]; then
	error "Script Cannot Be Started This Way, Exports Are Not Set."
fi

taskType=$(dialog --backtitle "Clone Deploy" --title "Select A Task" --clear --menu "" 20 60 15 1 Deploy 2 Upload 3 Multicast --stdout)


if [ "$taskType" != "1" ] && [ "$taskType" != "2" ] && [ "$taskType" != "3" ]; then
	error "Could Not Determine Task Type"
fi



if [ "$taskType" = "1" ]; then
	imageList=`$curlCommand --data "userId=0" "${web}ListImages" $curlEnd`
	imageId=$(dialog --backtitle "Clone Deploy" --title "Select An Image" --clear --menu "" 20 60 15 `parse_json "$imageList" .Images[]` --stdout)
	imageProfileList=`$curlCommand --data "imageId=$imageId" "${web}ListImageProfiles" $curlEnd`
	if [ "`parse_json "$imageProfileList" .Count`" = "1" ]; then
		imageProfileId=`parse_json "$imageProfileList" .FirstProfileId`
	else
		imageProfileId=$(dialog --backtitle "Clone Deploy" --title "Select An Image Profile" --clear --menu "" 20 60 15 `parse_json "$imageProfileList" .ImageProfiles[]` --stdout)
	fi
	
	ond_HostInfo "push"
	unicastInfo="${unicastInfo} multicast=false imgDirection=push"
	
elif [ "$taskType" = "2" ]; then
  image_list=`$curlCommand --data "userId=0" "${web}ListImages" $curlEnd`
  image_id=$(dialog --backtitle "Clone Deploy" --title "Select An Image" --clear --menu "" 20 60 15 `parse_json "$image_list" .Images[]` --stdout)
  profile_list=`$curlCommand --data "imageId=$image_id" "${web}ListImageProfiles" $curlEnd`
  if [ "$(parse_json "$profile_list" .Count)" = "1" ]; then
    image_profile_id=`parse_json "$profile_list" .FirstProfileId`
  else
    image_profile_id=$(dialog --backtitle "Clone Deploy" --title "Select An Image Profile" --clear --menu "" 20 60 15 `parse_json "$profile_list" .ImageProfiles[]` --stdout)
  fi
  ondemand_arguments=$($curlAuth --data "mac=$mac&profileId=$image_profile_id&taskType=pull" "${web}OnDemandTaskArgs" $curlEnd)
  ondemand_arguments="${ondemand_arguments} task=pull"
		
elif [ "$taskType" = "3" ]; then
	while [ "$sessionID" = "" ]; do
		if [ "$sessionID" = "" ]; then
			clear
			mcSessions=`curl -sSk -H "Authorization: "$(echo -n "$WDS_KEY" | base64)"" "${web}McSessions" --connect-timeout 10 --stderr -`
			i=0
			for session in $mcSessions; do
				i=$((i+1));
				echo $session;
				if [ "$i" = "20" ]; then
					echo
					echo -n " ...... Select A Session ID (Enter For More): "
					read sessionID;
					if [ -n "$sessionID" ]; then
						break
					fi
					clear
					i=0
				fi
			done
			echo
			if [ -n "$sessionID" ]; then
				break
			fi
		
			echo -n " ...... Select A Session ID (Enter To Repeat Listing): "
			read sessionID	
		fi		
	done
	echo
	
	imageID="0"
	ond_HostInfo "push"
	multicastInfo=`curl -sSk -H "Authorization: "$(echo -n "$WDS_KEY" | base64)"" -FmcTaskName="$(echo -n $sessionID | base64)" -Fmac="$(echo -n $mac | base64)" "${web}McInfo" --connect-timeout 10 --stderr -`
	for arg in "$multicastInfo"; do case "$arg" in *=*) eval $arg;; esac; done	
	unicastInfo="${unicastInfo} ${multicastInfo} multicast=true"

else
	error "An Error Occurred Or No Task Was Selected"
fi

 clear_and_move_down
if [ "$taskType" = "2" ]; then
	/bin/cd_pull "true" "$ondemand_arguments"
else
	if [ "$hostName" = "" ] || [ "$hostName" = "null" ]; then
		echo "This Computer Was Not Found In The Database, Enter A Name For It Now:"
		echo "Leave Blank To Skip Auto Host Renaming"
		echo
		read hostName
		echo 
		unicastInfo="${unicastInfo} hostName=$hostName"
	fi
	/bin/cd_push "true" "$unicastInfo"
fi