#!/bin/bash

. /bin/cd_global_functions

computer_id=$1
reporter_type=$2
cancel_test=$3

if [ "$cancel_test" = "true" ]; then
  while true; do
    result=$($curlAuth --data "computerId=$computer_id" "${web}CheckForCancelledTask" $curlEnd)
    if [ "$result" = "true" ]; then
      error "Task Has Been Cancelled"
    fi
    sleep 30
  done
fi
if [ "$reporter_type" = "partclone" ]; then
  while [ -f "/tmp/clone.progress" ]; do
    post=$(tail -n 1 /tmp/clone.progress)
	result=$($curlAuth --data "computerId=$computer_id&progress=$post&progressType=partclone" "${web}UpdateProgress" $curlEnd)        
     sleep 2
  done	
else
  while [ -f "/tmp/wim.progress" ]; do
    post=$(cat /tmp/wim.progress | dos2unix | sed -e 's/    /\n/g' | sed -e 's/done)/)\n/g' | tail -n 1)
	  if [ -z "$post" ]; then
	    post="Please Wait.  Making WIM Pipable."
	  fi
    result=$($curlAuth --data "computerId=$computer_id&progress=$post&progressType=wim" "${web}UpdateProgress" $curlEnd)        
    sleep 2
  done
fi

