#!/bin/sh

. functions
. cd_helpers


taskType=$(dialog --title "Clone Deploy" --menu "Select A Task" 10 30 3 1 Deploy 2 Upload 3 Multicast --stdout)


if [ "$taskType" != "1" ] && [ "$taskType" != "2" ] && [ "$taskType" != "3" ]; then
	error "Could Not Determine Task Type"
fi



if [ "$taskType" = "1" ]; then
	#imageList
	imagelist="1 \"image1\" 2 \"image 2\""
	taskType=$(dialog --title "Clone Deploy" --menu "Select An Image" 10 30 3 "$imagelist" --stdout)
	echo $imagelist
	ond_HostInfo "push"
	unicastInfo="${unicastInfo} multicast=false imgDirection=push"
	
elif [ "$taskType" = "2" ]; then
	uploadType=$(dialog --title "Clone Deploy" --menu "Select A Task" 10 30 3 1 "Upload New Image" 2 "Upload Existing Image" --stdout)
		
	if [ "$uploadType" != "1" ] && [ "$uploadType" != "2" ]; then
		error "Could Not Determine If This Is A New Or Existing Image"
	fi

	if [ "$uploadType" = "1" ]; then
		imgName=$(dialog --title "Clone Deploy" --inputbox "Enter An Image Name" 8 50 --stdout)
		echo -n " ...... Enter An Image Name: "
		read imgName
		echo
		
		clear
		echo " ** Creating Image ** "
		addImageResult=`curl -sSkX POST -H "Authorization: "$(echo -n "$WDS_KEY" | base64)"" -H "Content-type: application/json; charset=UTF-8" -d '{"image":{"Name":"'"${imgName}"'","OS":"'""'","Description":"","Protected":"0","IsVisible":"1","ClientSize":""} }' ${web}AddImage --connect-timeout 10 --stderr -`
		
		arr=$(echo $addImageResult | tr "," "\n");
			i=0;
			for x in $arr; do
   				imageID[i]=$x;
				i=$(( $i + 1 ))
			done		
		echo " ...... $addImageResult"
		echo
		ond_HostInfo "pull"
		unicastInfo="${unicastInfo} imageID=${imageID[0]} imgDirection=pull"
	else
		imageList
		ond_HostInfo "pull"
		unicastInfo="${unicastInfo} imgDirection=pull"
		
	fi
	
elif [ "$taskType" = "3" ]; then
	while [ "$sessionID" = "" ]; do
		if [ "$sessionID" = "" ]; then
			clear
			mcSessions=`curl -sSk -H "Authorization: "$(echo -n "$WDS_KEY" | base64)"" "${web}McSessions" --connect-timeout 10 --stderr -`
			i=0
			for session in $mcSessions; do
				i=$((i+1));
				echo $session;
				if [ "$i" = "20" ]; then
					echo
					echo -n " ...... Select A Session ID (Enter For More): "
					read sessionID;
					if [ -n "$sessionID" ]; then
						break
					fi
					clear
					i=0
				fi
			done
			echo
			if [ -n "$sessionID" ]; then
				break
			fi
		
			echo -n " ...... Select A Session ID (Enter To Repeat Listing): "
			read sessionID	
		fi		
	done
	echo
	
	imageID="0"
	ond_HostInfo "push"
	multicastInfo=`curl -sSk -H "Authorization: "$(echo -n "$WDS_KEY" | base64)"" -FmcTaskName="$(echo -n $sessionID | base64)" -Fmac="$(echo -n $mac | base64)" "${web}McInfo" --connect-timeout 10 --stderr -`
	for arg in "$multicastInfo"; do case "$arg" in *=*) eval $arg;; esac; done	
	unicastInfo="${unicastInfo} ${multicastInfo} multicast=true"

else
	error "An Error Occurred Or No Task Was Selected"
fi

if [ "$taskType" = "2" ]; then
	/bin/pull "true" "$unicastInfo"
else
	if [ "$hostName" = "" ] || [ "$hostName" = "null" ]; then
		echo "This Computer Was Not Found In The Database, Enter A Name For It Now:"
		echo "Leave Blank To Skip Auto Host Renaming"
		echo
		read hostName
		echo 
		unicastInfo="${unicastInfo} hostName=$hostName"
	fi
	/bin/push "true" "$unicastInfo"
fi