#!/bin/bash

. /bin/lie_global_functions

task_id=$1
reporter_type=$2

if [ "$reporter_type" = "partclone" ]; then
  while [ -f "/tmp/clone.progress" ]; do
    post=$(tail -n 1 /tmp/clone.progress)
    result=$($curlAuth --data "taskId=$task_id&progress=$post&progressType=partclone" "${web}UpdateProgress" $curlEnd)        
    sleep 2
  done	
else
  while [ -f "/tmp/wim.progress" ]; do
    post=$(cat /tmp/wim.progress | dos2unix | sed -e 's/done/\n/g' | tail -n 1)
	
	if [[ "$post" == *"scanned"* ]]; then
	  post="Scanning Files."
	fi
	 
    if [ -z "$post" ]; then
      post="Please Wait."
    fi
    
	result=$($curlAuth --data "taskId=$task_id&progress=$post&progressType=wim" "${web}UpdateProgress" $curlEnd)        
    sleep 2
  done
fi


