#!/bin/bash

. /bin/lie_global_functions
computer_id="$1"
while true; do
  result=$($curlAuth --data "computerId=$computer_id" "${web}CheckForCancelledTask" $curlEnd)
  if [ "$result" = "true" ]; then
    error "Task Has Been Cancelled" 3
  fi
  sleep 10
done


