#!/bin/bash
export LC_ALL=C
export LANG=C
CLIENT_LOG="/tmp/clientlog.log"

#diskutil seems to change often, handle different versions of diskutil
os_version=$(sw_vers -productVersion | cut -d. -f1 -f2)

if [ "$os_version" = "10.11" ]; then
  hd_size_param="Total Size:"
  partition_size_param="Total Size:"
  free_space_param="Volume Free Space:"
fi

if [ "$os_version" = "10.12" ] || [ "$os_version" = "10.13" ]; then
  hd_size_param="Disk Size:"
  partition_size_param="Disk Size:"
  free_space_param="Volume Available Space:"
fi

function get_volume_min_size()
{
  local volume_to_shrink="$1"
  
  if [ "$os_version" = "10.11" ]; then
    echo "$(diskutil resizeVolume $volume_to_shrink limits 2>> $CLIENT_LOG | grep "Minimum" | cut -d "(" -f2 | cut -d " " -f1)"
  fi
  
  if [ "$os_version" = "10.12" ] || [ "$os_version" = "10.13" ]; then
    echo "$(diskutil resizeVolume $volume_to_shrink limits 2>> $CLIENT_LOG | grep "Recommended minimum size" | cut -d "(" -f3 | cut -d " " -f1)"
  fi
}

#
#End of disk utility functions
#

function parse_json()
{
	echo `echo "$1" | jq "$2" -r`
}

function remove_whitespace() {
    local var="$*"
    var="${var#"${var%%[![:space:]]*}"}"   # remove leading whitespace characters
    var="${var%"${var##*[![:space:]]}"}"   # remove trailing whitespace characters
    echo -n "$var"
}

function error()
{
  local reboot_time=$2
	echo
	log " ** An Error Has Occurred ** " "display"
	log " ...... $1" "display"
	
	log " shrunk_volumes: $shrunk_volumes"
    unique_shrunk_volumes=$(echo $shrunk_volumes | xargs -n1 | sort -u | xargs)
    log " unique_shrunk_volumes: $unique_shrunk_volumes"
    log " ** Expanding Resized Volumes **" "display"
    echo
    for shrunk_volume in $unique_shrunk_volumes; do
      if /usr/sbin/diskutil info $shrunk_volume | grep "Logical Volume" > /dev/null; then
	    diskutil cs resizeVolume $shrunk_volume 0b 2>> $CLIENT_LOG
	  else
        diskutil resizeVolume $shrunk_volume R 2>> $CLIENT_LOG
	  fi
    done
  
	echo
	echo " ** Rebooting In One Minute ** "
	
	
	$curlAuth --data "taskId=$task_id&error=$1" "${web}ErrorEmail" $curlEnd
	
	
	$curlAuth -F computerId="$(echo -n $computer_id | base64)" -F logContents="$(cat /tmp/clientlog.log | base64)"  -F subType="$(echo -n $task | base64)"  -F mac="$(echo -n $mac | base64)" "${web}UploadLog" $curlEnd	
	
	if [ -n "$reboot_time" ]; then
	  sleep $reboot_time
	else
	  sleep 60
	fi
	if [ "$task_completed_action" = "Power Off" ]; then
		shutdown
	elif [ "$task_completed_action" = "Exit To Shell" ]; then
		/bin/bash
	else
		reboot
	fi 
}

function checkout()
{
	echo
	log " ** Closing Active Task ** " "display"
	cd /
	sleep 10
	umount /storage &> /dev/null
	
	if [ "$task" = "permanentdeploy" ]; then
	  checkout_status=$($curlAuth --data "taskId=$task_id" "${web}PermanentTaskCheckOut" $curlEnd)
	else
	  checkout_status=$($curlAuth --data "taskId=$task_id" "${web}CheckOut" $curlEnd)
	fi
	log " ...... $checkout_status" "display"
	
	echo
		
	$curlAuth -F computerId="$(echo -n $computer_id | base64)" -F logContents="$(cat /tmp/clientlog.log | base64)"  -F subType="$(echo -n $task | base64)"  -F mac="$(echo -n $mac | base64)" "${web}UploadLog" $curlEnd
		
	sleep 1;
	
	if [ "$task_completed_action" = "Power Off" ]; then
		shutdown
	elif [ "$task_completed_action" = "Exit To Shell" ]; then
		/bin/bash
	else
		reboot
	fi
	
}

function clear_and_move_down()
{
	clear
	local line=0
	while [ "$line" -le "6" ]; do
		line=$(( $line + 1 ))
		echo
	done
}

function log()
{
	echo "" >> $CLIENT_LOG;
	if [ "$2" = "display" ]; then
		echo "$1" | tee -a $CLIENT_LOG;
	else
		echo "$1" >> $CLIENT_LOG;
	fi
}

function get_hard_drives()
{
	local task_type="$1"
	local partitions
	local partition_count
	local partition
	hard_drives=""
	log " ** Looking For Hard Drive(s) ** "
	log " ...... Displaying Available Devices "
	diskutil list >> $CLIENT_LOG 2>&1
	diskutil corestorage list >> $CLIENT_LOG 2>&1
	diskutil apfs list >> $CLIENT_LOG 2>&1
	
	if [ -n "$custom_hard_drives" ]; then
		hard_drives="$custom_hard_drives"
		log " ...... Hard Drive(s) Set By Image Profile: $hard_drives"	
	else
	  if [ "$task_type" = "upload" ]; then
		all_hard_drives=$(diskutil list | grep "(internal\|(synthesized" | cut -d " " -f1)
		log "all_hard_drives: $all_hard_drives"
		for hdd in $all_hard_drives; do
		  disk_name=$(echo $hdd | sed 's~/dev/~~g')
		    #only get hard drives that have partitions.  No reason to try and upload a disk without partitions this also exludes lv's since they don't have partitions
			partition_count=0  
            partition_count=$(diskutil list | grep ${disk_name} | grep -vw ${disk_name} -c)
            if [ "$partition_count" -gt "0" ]; then
              hard_drives="$hard_drives $hdd "
			elif [ "$simple_upload_schema" = "true" ]; then
			  #when using a simple image schema add logical volumes to the hard drive list
			  if diskutil info $disk_name | grep "LV UUID" > /dev/null; then
			    hard_drives="$hard_drives $hdd "
			  fi
            fi
		done
	  else #deploy
	    #When deploying it is very possible the hard drive won't have a disk label so don't use the method used for uploads
	    hard_drives=$(diskutil list | grep "(internal\|(synthesized" | cut -d " " -f1)
	  fi
	fi
	
	hard_drive_count=0
	for hdd in $hard_drives; do	
		hard_drive_count=$(( $hard_drive_count + 1 ))
	done
		
	log " ...... Found $hard_drive_count Drive(s)" 
	log " ...... Drive(s): $hard_drives" 
	
	if [ "$hard_drive_count" = "0" ]; then
		error "Could Not Find A Hard Drive Attached To This Computer."
	fi
	sleep 2
	echo
}

function get_all_volume_uuids()
{
  all_volume_uuids=""
  log "Getting all volume uuids"

  local volume_uuid
  
  for partition in $partitions; do
    log "$partition"
    volume_uuid=$(diskutil info $partition | grep "Volume UUID:" | cut -d : -f2 | sed -e 's/^[ \t]*//')
    log "$volume_uuid"
	if [ -z "$volume_uuid" ]; then
	  volume_uuid=$(diskutil info $partition | grep "Partition UUID:" | cut -d : -f2 | sed -e 's/^[ \t]*//')
	fi
	all_volume_uuids="$all_volume_uuids $volume_uuid"
  done
  
  log "All volume uuids for $hard_drive"
  log "$all_volume_uuids"
  all_uuids_count=0  
  for vuuid in $all_volume_uuids; do
    all_uuids_count=$(( $all_uuids_count + 1 ))
  done
  log "$all_uuids_count"
}

function get_volume_uuid()
{
  local device_node
  device_node="$1"
  echo $(diskutil info $device_node | grep "Volume UUID:" | cut -d : -f2 | sed -e 's/^[ \t]*//')
}

function get_device_node()
{
  local uuid
  uuid="$1"
  echo $(diskutil info $uuid | grep "Device Node:" | cut -d : -f2 | sed -e 's/^[ \t]*//')
}

function get_partitions()
{
  local display_onscreen="$1"
  local partition
  
  if [ "$display_onscreen" = "true" ]; then
    log " ** Determining Partition Count On $hard_drive ** " "display"
  fi
  
  partitions=""
  if [ -n "$custom_partitions" ]; then
    for partition in $custom_partitions; do
      echo "$partition" | grep $hard_drive
      if [ "$?" = "0" ]; then
        partitions="$partitions $partition"
      fi
    done
	if [ "$display_onscreen" = "true" ]; then
	  log " ...... Partitions Set By Image Profile: $partitions" "display"
    fi
  else
    drive_name=$(echo $hard_drive | cut -d "/" -f 3)
    partitions_suffix=$(diskutil list | grep $drive_name | grep -vw $hard_drive | grep -vw $drive_name | grep -vi "volume on" | awk -F"$drive_name"  '{print $2}' )
	for suffix in $partitions_suffix; do
	  partitions="$partitions $hard_drive$suffix"
	done
  fi
    
  partition_count=0  
  for partition in $partitions; do
    partition_count=$(( $partition_count + 1 ))
  done
  
  if [ "$display_onscreen" = "true" ]; then
    log " ...... Found $partition_count Partition(s)" "display"
	log " ...... $partitions"
  fi
}

function process_scripts()
{
  local scripts="$1"
  for script_id in $scripts; do
    $curlAuth --data "scriptId=$script_id" "${web}GetCustomScript" $curlEnd > /tmp/custom_script
	log " ** Running Custom Script With Id $script_id ** " "display"
	sleep 5
	#source script in sub shell so the values of the core script do not get overwritten
	( . /tmp/custom_script )
  done
}

function mount_smb()
{
	local mount_result
	local all_cluster_dps
	local result
	
	log " ** Mounting SMB Share **" "display"
	mkdir /storage >> $CLIENT_LOG 2>&1
	
	mount | grep "on /storage" >> /dev/null 2>&1
	if [ "$?" = "0" ]; then
	  #already mounted
	  log " ...... Success" "display"
	  echo
	  return 0
	fi
	
	smbInfo=$($curlAuth --data "dpId=$dp_id&task=$task" "${web}DistributionPoint" $curlEnd)
	log " ...... Connecting To $(parse_json "$smbInfo" .DisplayName)" "display"
	#fix path that was originally only used for initrd
	share_path=$(echo "$(parse_json "$smbInfo" .SharePath)" | sed 's~//~~g')
	
	mount_result=$(mount_smb_sub "$smbInfo")
	if [ "$mount_result" = "true" ]; then
	  log " ...... Success" "display"
	else
	  #Look for other distribution points
	  log " ...... Looking For Additional Distribution Points"
	  all_cluster_dps=$($curlAuth --data "computerId=$computer_id" "${web}GetAllClusterDps" $curlEnd)
	  if [ ! "$?" = "0" ]; then
		error "Could Not Find Additional Distribution Points"
	  else
	    if [ "$all_cluster_dps" = "single" ]; then
			error "Could Not Mount SMB Share and Server Is Not Clustered"
		elif [ "$all_cluster_dps" = "false" ]; then
			error "Could Not Mount SMB Share and An Unknown Error Occurred While Looking For Others"
		else
			for local_dp_id in $all_cluster_dps; do
			  sleep 2
			  smbInfo=$($curlAuth --data "dpId=$local_dp_id&task=$task" "${web}DistributionPoint" $curlEnd)
			  log " ...... Connecting To $(parse_json "$smbInfo" .DisplayName)" "display"
			  if [ "smb_debug" = "1" ]; then
				log "$smbInfo"
			  fi
			  mount_result=$(mount_smb_sub "$smbInfo")
			  if [ "$mount_result" = "true" ]; then
			    log " ...... Success" "display"
				dp_id=$local_dp_id
				result="true"
				break
			  else
			    result="false"
			  fi
			done
			
			if [ "$result" = "false" ]; then
			  #no smb shares could be mounted
			  error "Could Not Mount Any Available SMB Shares"
			fi
		fi
	  fi
	fi
    
	echo
	sleep 2
}

function mount_smb_sub()
{
	local smbInfo=$1
	share_path=$(echo "$(parse_json "$smbInfo" .SharePath)" | sed 's~//~~g')
	mount -t smbfs //"$(parse_json "$smbInfo" .Domain)"\;"$(parse_json "$smbInfo" .Username)":"$(parse_json "$smbInfo" .Password)"@"$share_path" /storage 2>/tmp/mntstat
		
	if [ ! $? = "0" ]; then
	  cat /tmp/mntstat >> $CLIENT_LOG
	  log "Could Not Mount SMB Share: $(cat /tmp/mntstat)" "display"
	  echo "false"
	else
	  cd /storage/images/$image_name;
	  if [ "$?" != "0" ]; then
	    log "Could Not Change Directory To /storage/images/$image_name Check Permissions" "display"
		echo "false"
		umount /storage &> /dev/null
	  else
	    echo "true"
	  fi
	fi
}

function process_file_copy()
{
  local current_object="$1"
  local object_type="$2"
  local array_index=-1
   log " ** Processing File Copy ** " "display"
   sleep 5
  while [  "$(( $array_index + 1 ))" -lt "$(parse_json "$file_copy_schema" .Count)" ]; do
    array_index=$(( $array_index + 1))
    current_file="$(parse_json "$file_copy_schema" .FilesAndFolders[$array_index])"
    log "$current_file"
	  
	    log "Copying /storage/resources/$(parse_json "$current_file" .SourcePath)"
		
		  if [ -d "/storage/resources/$(parse_json "$current_file" .SourcePath)" ]; then
		    if [ "$(parse_json "$current_file" .FolderCopyType)" = "Folder" ]; then
		      cp -R "/storage/resources/$(parse_json "$current_file" .SourcePath)" "/Volumes/$osx_target_volume/$(parse_json "$current_file" .DestinationFolder)/" 2>>$CLIENT_LOG
			else #FolderCopyType = contents
			  cp -R "/storage/resources/$(parse_json "$current_file" .SourcePath)/." "/Volumes/$osx_target_volume/$(parse_json "$current_file" .DestinationFolder)/" 2>>$CLIENT_LOG
			fi		
		  else
            cp "/storage/resources/$(parse_json "$current_file" .SourcePath)" "/Volumes/$osx_target_volume/$(parse_json "$current_file" .DestinationFolder)/" 2>>$CLIENT_LOG
		  fi
  done
}
