#!/bin/bash

. /usr/local/bin/osx_global_functions

clear_and_move_down
echo " ** Computer Registration ** "
echo

mac=$(networksetup -listallhardwareports | grep "Ethernet Address:" | cut -d " " -f 3 | head -n1)
echo " ** System MAC Address: $mac ** "
echo

while [ "$isError" != "false" ]; do
	
	echo " ** Enter A Computer Name To Register.  Leave Blank To Skip Registration. ** "
	echo
	echo -n "Computer Name: "
	read name
	if [ -z "$name" ]; then 
		echo
		break;
	fi
	echo
		registerResult=$($curlAuth --data "name=$name&mac=$mac" ${web}AddComputer $curlClose)
		if [ ! "$?" = "0" ]; then
			echo " ...... Could Not Register Computer: $registerResult"
		else
			if [ "$(parse_json "$registerResult" .Success)" = "true" ]; then
				echo " ...... Success"
				isError="false"
			else
				echo " ...... $(parse_json "$registerResult" .ErrorMessage)"
				isError="true"
			fi
			echo
		fi
done




