#!/bin/bash
CLIENT_LOG="/tmp/clientlog.log"

function set_curl_command()
{
	export curlCommand="curl -sSk"
	export curlEnd=" --connect-timeout 10 --stderr -"
	export curlEndRedirect=" --connect-timeout 10 --stderr - >> /tmp/clientlog.log"
}

function set_curl_auth()
{
	export curlAuth="curl -sSk -H Authorization:$(echo -n "$USER_TOKEN" | base64)"
}

function clear_and_move_down()
{
	clear
	local line=0
	while [ "$line" -le "6" ]; do
		line=$(( $line + 1 ))
		echo
	done
}

function parse_json()
{
	echo `echo "$1" | jq "$2" -r`
}

function remove_whitespace() {
    local var="$*"
    var="${var#"${var%%[![:space:]]*}"}"   # remove leading whitespace characters
    var="${var%"${var##*[![:space:]]}"}"   # remove trailing whitespace characters
    echo -n "$var"
}

function checkin()
{	
	log " ** Looking For Active Task ** " "display"
	checkInStatus=`$curlAuth --data "computerMac=$mac" "${web}CheckIn" $curlEnd`
	if [ ! "$?" = "0" ]; then
		error "$checkInStatus"
	else
		if [ "`parse_json "$checkInStatus" .Result`" != "true" ]; then
			error "`parse_json "$checkInStatus" .Message`"
		else
			sleep 1
			for arg in "`parse_json "$checkInStatus" .TaskArguments`"; do case "$arg" in *=*) eval "$arg"; log "$arg"; esac; done
			log " ...... Success" "display"
		fi
	fi
	
	if [ "$web_cancel" = "true" ] && [ "$is_ondemand" != "true" ]; then
	  cd_cancel $computer_id &
	fi
	echo
	sleep 2
}

function checkout()
{
	echo
	log " ** Closing Active Task ** " "display"
	cd /
	sleep 10
	umount /storage &> /dev/null
	
	cat /tmp/clientlog.log | grep -v "percent completed" > /tmp/cleanedlog.log
	
	if [ "$multicast" = "true" ]; then
	mccheckoutResult=$($curlAuth --data "portBase=$multicast_port" "${web}MulticastCheckOut" $curlEnd)
		log " ...... $mccheckoutResult"
	fi
		
	if [ "$is_ondemand" != "true" ]; then
	  checkout_status=$($curlAuth --data "computerId=$computer_id" "${web}CheckOut" $curlEnd)
	  log " ...... $checkout_status" "display"
	else
	  if [ -z "$computer_id"  ]; then
	  computer_id="-1"
	  fi
	fi
	
	echo
		
	$curlAuth -F computerId="$(echo -n $computer_id | base64)" -F logContents="$(cat /tmp/cleanedlog.log | base64)"  -F subType="$(echo -n $task | base64)"  -F mac="$(echo -n $mac | base64)" "${web}UploadLog" $curlEnd
		
	sleep 1;
	
	if [ "$task_completed_action" = "Power Off" ]; then
		poweroff;
	elif [ "$task_completed_action" = "Exit To Shell" ]; then
		/bin/bash
	else
		reboot -f
	fi
	
}




function error()
{
  local reboot_time=$2
	echo
	log " ** An Error Has Occurred ** " "display"
	log " ...... $1" "display"
	echo
	echo " ** Rebooting In One Minute ** "
	
	cat /tmp/clientlog.log | grep -v "percent completed" > /tmp/cleanedlog.log
	
	if [ -z "$computer_id"  ]; then
	  computer_id="-1"
	else
	  $curlAuth --data "computerId=$computer_id&error=$1" "${web}ErrorEmail" $curlEnd
	fi
	
	$curlAuth -F computerId="$(echo -n $computer_id | base64)" -F logContents="$(cat /tmp/cleanedlog.log | base64)"  -F subType="$(echo -n $task | base64)"  -F mac="$(echo -n $mac | base64)" "${web}UploadLog" $curlEnd	
	
	if [ -n "$reboot_time" ]; then
	  sleep $reboot_time
	else
	  sleep 60
	fi
	if [ "$task_completed_action" = "Power Off" ]; then
		poweroff;
	elif [ "$task_completed_action" = "Exit To Shell" ]; then
		/bin/bash;
	else
		reboot -f
	fi 
}

function expand_volume()
{

	local partition="$1"
	local filesystem="$2"
	
	echo
	if [ "$filesystem" = "ext2" ] || [ "$filesystem" = "ext3" ] || [ "$filesystem" = "ext4" ]; then
		log " ** Expanding EXT Volume On $1 ** " "display"
		partprobe &>/dev/null;
		sleep 5

		resize2fs $1 &>/dev/null
		
		if [ ! "$?" = "0" ]; then
			log "Warning, EXT File System Did Not Resize Properly.  Check Your Disk Size After Booting" "display"
			$curlAuth --data "computerId=$computer_id&error=Ext Volume Did Not Expand Properly" "${web}ErrorEmail" $curlEnd
		else
			log " ...... Success" "display"
		fi
		echo
		e2fsck -fp $1 &>/dev/null
	
	elif [ "$filesystem" = "ntfs" ]; then
	  ntfsfix -b -d $1 &>>$CLIENT_LOG
		volumeSize=`ntfsresize -f -i -P $1 | grep -i "current volume size:" | cut -d " " -f4`
		deviceSize=`ntfsresize -f -i -P $1 | grep -i "current device size:" | cut -d " " -f4`
		volumeMargin=$(( $deviceSize - $volumeSize ))
		log " volumeMargin: $volumeMargin"
		if [ "$volumeMargin" -lt "104857600" ]; then
			return 0
		fi
		log " ** Expanding NTFS Volume on $1 ** " "display"

		partprobe &>/dev/null;
		sleep 5
			
		#Found That expanding all the way sometimes corrupted the filesystem
		deviceSize=$(( $deviceSize - 10485760 )) #Don't expand too far
		log "Expanding NTFS Volume To: $deviceSize"
		ntfsresize -f -b -s $deviceSize $1 &>> $CLIENT_LOG << CONFIRM
y
CONFIRM

		if [ ! "$?" = "0" ]; then
			log "Warning, NTFS File System Did Not Resize Properly.  Check Your Disk Size After Booting To Windows" "display"
			$curlAuth --data "computerId=$computer_id&error=Ntfs Volume Did Not Expand Properly" "${web}ErrorEmail" $curlEnd
		else
			log " ...... Success" "display"
		fi
	
		echo 
		ntfsfix -b -d $1 &>>$CLIENT_LOG
	fi

}

function get_hard_drives()
{
	log " ** Looking For Hard Drive(s) ** " "display"
	log " ...... Displaying Available Devices "
	blockdev --report &>> $CLIENT_LOG
	fdisk -l &>> $CLIENT_LOG
	
	if [ -n "$custom_hard_drives" ]; then
		hard_drives="$custom_hard_drives"
		log " ...... Hard Drive(s) Set By Image Profile: $hard_drives" "display"		
	else
		hard_drives=`lsblk -ipdno KNAME`	
	fi
	
	hard_drive_count=0
	for hdd in $hard_drives; do	
		hard_drive_count=$(( $hard_drive_count + 1 ))
	done
		
	log " ...... Found $hdCount Drive(s)" "display"
	log " ...... Drive(s): $hard_drives" "display"
	
	if [ "$hard_drive_count" = "0" ]; then
		error "Could Not Find A Hard Drive Attached To This Computer.  Try A Different Kernel."
	fi
	sleep 2
	echo
}

function log()
{
	echo "" >> $CLIENT_LOG
	if [ "$2" = "display" ]; then
		echo "$1" | tee -a $CLIENT_LOG
	else
		echo "$1" >> $CLIENT_LOG
	fi
}

function log_boot_args()
{
	log " ** Displaying Boot Arguments ** "
	log "$(cat /proc/cmdline) MAC: $mac"
	uname -a >> $CLIENT_LOG
	log "Boot Image Version: $(cat /etc/cd_version)"
}


function mount_smb()
{
	log " ** Mounting SMB Share **" "display"
	mkdir /storage &>> $CLIENT_LOG
	smbInfo=$($curlAuth --data "dpId=$dp_id&task=$task" "${web}DistributionPoint" $curlEnd)
	for smbVersion in 3.0 2.1 2.0 1.0; do	
		mount -t cifs "$(parse_json "$smbInfo" .SharePath)" /storage -o user="$(parse_json "$smbInfo" .Username)",pass="$(parse_json "$smbInfo" .Password)",dom="$(parse_json "$smbInfo" .Domain)",vers=$smbVersion 2>/tmp/mntstat
		if [ ! $? = "0" ]; then
			cat /tmp/mntstat >> $CLIENT_LOG
			errormsg=$(cat /tmp/mntstat)
			
		else
			log " ...... Success" "display"

			cd /storage/images/$imgName;
			if [ "$?" != "0" ]; then
				error "Could Not Change Directory To /images/$imgName Check Permissions"
			fi
			break
		fi
		if [ "$smbVersion" = "1.0" ]; then
			error "Could Not Mount SMB Share"
		fi
	done
	echo
	sleep 2
}

function process_scripts()
{
  local scripts="$1"
  for script_id in $scripts; do
    $curlAuth --data "scriptId=$script_id" "${web}GetCustomScript" $curlEnd > /tmp/custom_script
	log " ** Running Custom Script With Id $script_id ** " "display"
	sleep 5
	#source script in sub shell so the values of the core script do not get overwritten
	( . /tmp/custom_script )
  done
}

function process_sysprep_tags()
{
  local partition="$1"
  log " ** Processing Sysprep Tags On $partition ** " "display"
  sleep 5
  mkdir /mnt/ntfs &> /dev/null	
  ntfs-3g -o force,rw,remove_hiberfile $partition /mnt/ntfs &>/dev/null
  if [ "$?" != "0" ]; then
    log "Could Not Mount NTFS To Change Answer File"
	return 1
  fi
  
  if [ -f "/mnt/ntfs/Windows/Panther/unattend.xml" ]; then
    log " ...... Found Answer File At /Windows/Panther/unattend.xml, Updating Answer File" "display"
	for tag_id in $sysprep_tags; do
      sysprep_tag_json=$($curlAuth --data "tagId=$tag_id" "${web}GetSysprepTag" $curlEnd)
	  perl -0777 -i -pe "s/($(parse_json "$sysprep_tag_json" .OpeningTag)).*($(parse_json "$sysprep_tag_json" .ClosingTag))/\$1$(parse_json "$sysprep_tag_json" .Contents)\$2/s" /mnt/ntfs/Windows/Panther/unattend.xml
    done
  elif [ -f "/mnt/ntfs/Windows/System32/sysprep/Panther/unattend.xml" ]; then
     log " ...... Found Answer File At /Windows/System32/sysprep/Panther/unattend.xml"
	 for tag_id in $sysprep_tags; do
      sysprep_tag_json=$($curlAuth --data "tagId=$tag_id" "${web}GetSysprepTag" $curlEnd)
	  perl -0777 -i -pe "s/($(parse_json "$sysprep_tag_json" .OpeningTag)).*($(parse_json "$sysprep_tag_json" .ClosingTag))/\$1$(parse_json "$sysprep_tag_json" .Contents)\$2/s" /mnt/ntfs/Windows/System32/sysprep/Panther/unattend.xml
    done
  else
    log " ...... Could Not Find Answer File"
  fi
  umount /mnt/ntfs
}

function process_file_copy()
{
  local current_object="$1"
  local object_type="$2"
  local array_index=-1
   log " ** Processing File Copy ** " "display"
   sleep 5
  while [  "$(( $array_index + 1 ))" -lt "$(parse_json "$file_copy_schema" .Count)" ]; do
    array_index=$(( $array_index + 1))
    current_file="$(parse_json "$file_copy_schema" .FilesAndFolders[$array_index])"
    log "$current_file"
	if [ "$object_type" = "partition" ]; then
	  if [ "$(parse_json "$current_object" .Number)" = "$(parse_json "$current_file" .DestinationPartition)" ]; then
	    log "Copying /storage/resources/$(parse_json "$current_file" .SourcePath)"
		if [ "$(parse_json "$current_object" .FileSystem)" = "ntfs" ]; then
          mkdir /mnt/fs &> /dev/null
		  ntfs-3g -o force,rw,remove_hiberfile ${hard_drive}${partition_prefix}$(parse_json "$current_object" .Number) /mnt/fs &>/dev/null
          if [ "$?" != "0" ]; then
            log "Could Not Mount NTFS"
	        return 1
          fi
		else # only ext or xfs
		  mkdir /mnt/fs &> /dev/null
		  mount ${hard_drive}${partition_prefix}$(parse_json "$current_object" .Number) /mnt/fs
		   if [ "$?" != "0" ]; then
             log "Could Not Mount Filesystem"
	         return 1
           fi
		fi
		  if [ -d "/storage/resources/$(parse_json "$current_file" .SourcePath)" ]; then
		    if [ "$(parse_json "$current_file" .FolderCopyType)" = "Folder" ]; then
		      cp -R "/storage/resources/$(parse_json "$current_file" .SourcePath)" "/mnt/fs/$(parse_json "$current_file" .DestinationFolder)/" &>>$CLIENT_LOG
			else #FolderCopyType = contents
			  cp -R "/storage/resources/$(parse_json "$current_file" .SourcePath)/." "/mnt/fs/$(parse_json "$current_file" .DestinationFolder)/" &>>$CLIENT_LOG
			fi		
		  else
            cp "/storage/resources/$(parse_json "$current_file" .SourcePath)" "/mnt/fs/$(parse_json "$current_file" .DestinationFolder)/" &>>$CLIENT_LOG
		  fi
	  fi
	else # object_type = lvm
	  if [ "$object_type" = "$(parse_json "$current_file" .DestinationPartition)" ]; then
	    log "Copying /storage/resources/$(parse_json "$current_file" .SourcePath)"
		if [ "$(parse_json "$current_object" .FileSystem)" = "ntfs" ]; then
          mkdir /mnt/fs &> /dev/null
		  ntfs-3g -o force,rw,remove_hiberfile /dev/mapper/$object_type /mnt/fs &>/dev/null
          if [ "$?" != "0" ]; then
            log "Could Not Mount NTFS"
	        return 1
          fi
		else # only ext or xfs
		  mkdir /mnt/fs &> /dev/null
		  mount /dev/mapper/$object_type /mnt/fs
		   if [ "$?" != "0" ]; then
             log "Could Not Mount Filesystem"
	         return 1
           fi
		fi
		  if [ -d "/storage/resources/$(parse_json "$current_file" .SourcePath)" ]; then
		    if [ "$(parse_json "$current_file" .FolderCopyType)" = "Folder" ]; then
		      cp -R "/storage/resources/$(parse_json "$current_file" .SourcePath)" "/mnt/fs/$(parse_json "$current_file" .DestinationFolder)/" &>>$CLIENT_LOG
			else #FolderCopyType = contents
			  cp -R "/storage/resources/$(parse_json "$current_file" .SourcePath)/." "/mnt/fs/$(parse_json "$current_file" .DestinationFolder)/" &>>$CLIENT_LOG
			fi		
		  else
            cp "/storage/resources/$(parse_json "$current_file" .SourcePath)" "/mnt/fs/$(parse_json "$current_file" .DestinationFolder)/" &>>$CLIENT_LOG
		  fi
		fi
	fi
	umount /mnt/fs
  done
}

function update_registry_key()
{
  local root="$1"
  local key="$2"
  local value="$3"
  reged -e "$root" &>>$CLIENT_LOG  <<EOFN 
ed $key
$value
q
y
EOFN
}

