#!/bin/bash

. /bin/cd_global_functions

if [ "$started_from_init" != "true" ]; then
	error "Script Cannot Be Started This Way, Exports Are Not Set."
fi

taskType=$(dialog --backtitle "Clone Deploy" --title "Select A Task" --clear --menu "" 20 60 15 1 Deploy 2 Upload 3 Multicast --stdout)

if [ "$taskType" != "1" ] && [ "$taskType" != "2" ] && [ "$taskType" != "3" ]; then
	error "Could Not Determine Task Type"
fi

if [ "$taskType" = "1" ]; then
	imageList=`$curlAuth --data "userId=$user_id" "${web}ListImages" $curlEnd`
	imageId=$(dialog --backtitle "Clone Deploy" --title "Select An Image" --clear --menu "" 20 60 15 `parse_json "$imageList" .Images[]` --stdout)
	imageProfileList=`$curlAuth --data "imageId=$imageId" "${web}ListImageProfiles" $curlEnd`
	if [ "`parse_json "$imageProfileList" .Count`" = "1" ]; then
		imageProfileId=`parse_json "$imageProfileList" .FirstProfileId`
	else
		imageProfileId=$(dialog --backtitle "Clone Deploy" --title "Select An Image Profile" --clear --menu "" 20 60 15 `parse_json "$imageProfileList" .ImageProfiles[]` --stdout)
	fi	
	ond_args=$($curlAuth --data "mac=$mac&objectId=$imageProfileId&task=push" "${web}GetOnDemandArguments" $curlEnd)
	ond_args="${ond_args} task=push"
    
elif [ "$taskType" = "2" ]; then
  image_list=`$curlAuth --data "userId=$user_id" "${web}ListImages" $curlEnd`
  image_id=$(dialog --backtitle "Clone Deploy" --title "Select An Image" --clear --menu "" 20 60 15 `parse_json "$image_list" .Images[]` --stdout)
  profile_list=`$curlAuth --data "imageId=$image_id" "${web}ListImageProfiles" $curlEnd`
  if [ "$(parse_json "$profile_list" .Count)" = "1" ]; then
    image_profile_id=`parse_json "$profile_list" .FirstProfileId`
  else
    image_profile_id=$(dialog --backtitle "Clone Deploy" --title "Select An Image Profile" --clear --menu "" 20 60 15 `parse_json "$profile_list" .ImageProfiles[]` --stdout)
  fi
  ond_args=$($curlAuth --data "mac=$mac&objectId=$image_profile_id&task=pull" "${web}GetOnDemandArguments" $curlEnd)
  ond_args="${ond_args} task=pull"
		
elif [ "$taskType" = "3" ]; then
	multicastList=`$curlAuth "${web}ListMulticasts" $curlEnd`
	multicastId=$(dialog --backtitle "Clone Deploy" --title "Select A Multicast Session" --clear --menu "" 20 60 15 `parse_json "$multicastList" .Multicasts[]` --stdout)
    ond_args=$($curlAuth --data "mac=$mac&objectId=$multicastId&task=multicast" "${web}GetOnDemandArguments" $curlEnd)
	ond_args="${ond_args} task=push"
else
	error "An Error Occurred Or No Task Was Selected"
fi

clear_and_move_down
if [ "$taskType" = "2" ]; then
	/bin/cd_pull "true" "$ond_args"
else
    for arg in "$ond_args"; do case "$arg" in *=*) eval "$arg"; esac; done
	if [ "$computer_name" = "" ] || [ "$computer_name" = "null" ]; then
		echo "This Computer Was Not Found In The Database, Enter A Name For It Now:"
		echo "Leave Blank To Skip Computer Renaming"
		echo
		read computer_name
		echo
		if [ -n "$computer_name" ]; then
		  ond_args="${ond_args} computer_name=$computer_name"
		fi
	fi
	/bin/cd_push "true" "$ond_args"
fi
