#!/bin/bash

. /bin/cd_global_functions

if [ "$started_from_init" != "true" ]; then
	error "Script Cannot Be Started This Way, Exports Are Not Set."
fi

function process_hard_drives()
{
  local drive_name
  local lbs
  local drive_size_block
  
  get_hard_drives "deploy"

  imaged_schema_drives=""
  current_hd_number=-1
  for hard_drive in $hard_drives; do
    echo
    log " ** Processing $hard_drive ** " "display"
    current_hd_number=$(( $current_hd_number + 1 ))
	
	if [ -n "$pre_scripts" ]; then
	  process_scripts "$pre_scripts"
	fi
	
    drive_name=$(echo $hard_drive | cut -d "/" -f 3)
    lbs=$(cat /sys/block/$drive_name/queue/logical_block_size)
	drive_size_block=$(blockdev --getsz $hard_drive) #Always outputs for 512 byte sectors, needs changed for other sector sizes
    if [ "$lbs" = "4096" ]; then
	  drive_size_block=$(( $drive_size_block / 8 ))
	fi
 
    drive_size_bytes=$(expr $lbs '*' $drive_size_block)
	
    log "Get hd_schema:  profileId=$profile_id&clientHdNumber=$current_hd_number&newHdSize=$drive_size_bytes&schemaHds=$imaged_schema_drives&clientLbs=$lbs"
    hd_schema=$($curlAuth --data "profileId=$profile_id&clientHdNumber=$current_hd_number&newHdSize=$drive_size_bytes&schemaHds=$(remove_whitespace $imaged_schema_drives)&clientLbs=$lbs" "${web}CheckHdRequirements" $curlEnd)
    log "$hd_schema"
	
    image_hd_to_use=$(parse_json "$hd_schema" .SchemaHdNumber)
    image_path=/storage/images/$image_name/hd$image_hd_to_use
	
    create_partition_layout
	
    process_partitions
	
	#Only update BCD for mbr.  EFI BCD is based on GUID's not offsets which are restored to the partitions, keeping the BCD intact.
	#In the future if I decided to randomize guid's the BCD for efi will also need updated
	if [ "$(parse_json "$hd_schema" .PartitionType)" = "mbr" ]; then
      update_bcd
	fi
	
    update_grub
	
    if [ "$(parse_json "$hd_schema" .PartitionType)" = "gpt" ]; then
	  log " ** Restoring GUID On $hard_drive ** "
	  sgdisk $hard_drive -U$(parse_json "$hd_schema" .Guid) &>> $CLIENT_LOG
	  
	  #hard drive and partition guids must be restored prior to updating nvram
	  update_efi_nvram
	fi
	
    imaged_schema_drives="$imaged_schema_drives $(parse_json "$hd_schema" .SchemaHdNumber) "
	
	if [ -n "$post_scripts" ]; then
	  process_scripts "$post_scripts"
	fi
done
}


function process_lvm()
{
  local array_index=-1
  local volume_group="$(parse_json "$current_partition" .VolumeGroup.Name)"
  local make_swap_result
  local current_logical_volume
  local escaped_lv_name
  
   volume_group=$(echo $volume_group | sed 's/-/--/g')
  while [  "$(( $array_index + 1 ))" -lt "$(parse_json "$current_partition" .VolumeGroup.LogicalVolumeCount)" ]; do
    array_index=$(( $array_index + 1))
    clear_and_move_down
    current_logical_volume="$(parse_json "$current_partition" .VolumeGroup.LogicalVolumes[$array_index])"
	log "$current_logical_volume"
    escaped_lv_name=$(echo $(parse_json "$current_logical_volume" .Name) | sed 's/-/--/g')
	
	if [ "$(parse_json "$current_logical_volume" .FileSystem)" = "swap" ]; then
      log "Creating Swap On $volume_group-$escaped_lv_name"
      log "$(parse_json "$current_logical_volume" .Uuid)"
      mkswap /dev/mapper/$volume_group-$escaped_lv_name -U $(parse_json "$current_logical_volume" .Uuid) &>> /tmp/makeswap
      cat /tmp/makeswap >>$CLIENT_LOG
      make_swap_result=$(cat /tmp/makeswap | grep "parsing UUID failed")
      if [ "$?" = "0" ]; then
        log " ...... Swap Creation Failed, Creating Swap With New UUID "
        mkswap /dev/mapper/$volume_group-$escaped_lv_name &>> $CLIENT_LOG
      fi
      continue
    fi
				
    download_image "$current_logical_volume" "$volume_group-$escaped_lv_name"
	
	if [ "$skip_expand_volumes" != "true" ]; then 
      if [ "$(parse_json "$current_logical_volume" .ImageType)" = "Block" ]; then
        expand_volume /dev/mapper/$volume_group-$escaped_lv_name $(parse_json "$current_logical_volume" .FileSystem)  
      fi
    fi
	
	if [ "$file_copy" = "True" ]; then
	  process_file_copy "$current_logical_volume" "$volume_group-$escaped_lv_name"
	fi
    clear_and_move_down
  done
}

function process_partitions()
{
  local partition_size_mb
  local array_index=-1
  
  if [ "$file_copy" = "True" ]; then
    log "file_copy_schema: profileId=$profile_id"
	 file_copy_schema=$($curlAuth --data "profileId=$profile_id" "${web}GetFileCopySchema" $curlEnd)
  fi
	
  while [  "$(( $array_index + 1 ))" -lt "$(parse_json "$hd_schema" .PhysicalPartitionCount)" ]; do
    array_index=$(( $array_index + 1))
    clear_and_move_down
    current_partition="$(parse_json "$hd_schema" .PhysicalPartitions[$array_index])"
    log "$current_partition"
	
    if [ -n "$(parse_json "$current_partition" .VolumeGroup)" ] && [ "$(parse_json "$current_partition" .VolumeGroup)" != "null" ]; then
      process_lvm
      continue
    fi
	
	#Only restore extended partition if the hd is the same size as the original
	if [ "$(parse_json "$current_partition" .Type)" = "extended" ]; then
	  if [ "$(parse_json "$hd_schema" .IsValid)" != "original" ] || [ "$force_dynamic_partitions" = "true" ]; then
	    continue
      fi
	fi
	
	get_partitions_according_to_mbr_gpt
	partition_counter=0
	for partition in $mbr_gpt_partitions; do
      partition_counter=$(( $partition_counter + 1 ))
      partition_number=`echo $partition | awk -F $hard_drive ' {print $2}' | sed 's/[^0-9]//g'`
     if [ "$(parse_json "$current_partition" .Number)" = "$partition_number" ]; then
	    partition_prefix=$(echo $partition | awk -F $hard_drive ' {print $2}' | sed 's/[0-9]*//g')
		break
	  else
        partition_prefix=""
      fi
	done
	
    if [ "$(parse_json "$current_partition" .FileSystem)" = "swap" ]; then
      log "Creating Swap On $hard_drive${partition_prefix}$(parse_json "$current_partition" .Number)"
      log "$(parse_json "$current_partition" .Uuid)"
      mkswap ${hard_drive}${partition_prefix}$(parse_json "$current_partition" .Number) -U $(parse_json "$current_partition" .Uuid) &>> $CLIENT_LOG	
      continue
    fi
			
    download_image "$current_partition" part
		
	partition_size_bytes=$(parted -s $hard_drive unit b print all | grep " $(parse_json "$current_partition" .Number) " -m 1 | awk -F' ' '{print $4}' | sed 's/B//g')

    if [ "$skip_expand_volumes" != "true" ]; then 
      if [ "$(parse_json "$current_partition" .ImageType)" = "Block" ] && [ "$partition_size_bytes" -gt "5368709120" ]; then #partition smaller than 5GB probably that way for a reason, leave it alone.
        expand_volume ${hard_drive}${partition_prefix}$(parse_json "$current_partition" .Number) $(parse_json "$current_partition" .FileSystem)  
      fi
    fi
		
    if [ "$(parse_json "$hd_schema" .PartitionType)" = "gpt" ]; then
      log " ** Restoring GUID On ${hard_drive}$(parse_json "$current_partition" .Number) ** "
      log " ...... part $part gptGUID: $gptGUID "
      sgdisk $hard_drive -u$(parse_json "$current_partition" .Number):$(parse_json "$current_partition" .Guid) &>> $CLIENT_LOG
    fi
		
    if [ "$(parse_json "$hd_schema" .BootPartition)" = "$(parse_json "$current_partition" .Number)" ] && [ "$(parse_json "$current_partition" .FileSystem)" = "ntfs" ]; then
      fix_ntfs_boot ${hard_drive}${partition_prefix}$(parse_json "$current_partition" .Number)
    fi
	
	#Todo: Add support for linux change name
	if [ "$(parse_json "$current_partition" .FileSystem)" = "ntfs" ] && [ -n "$computer_name" ] && [ "$change_computer_name" = "true" ]; then
      change_computer_name ${hard_drive}${partition_prefix}$(parse_json "$current_partition" .Number)
	fi
	
	if [ "$(parse_json "$current_partition" .FileSystem)" = "ntfs" ] && [ -n "$sysprep_tags" ]; then
      process_sysprep_tags  ${hard_drive}${partition_prefix}$(parse_json "$current_partition" .Number)
	fi
	
	if [ "$(parse_json "$current_partition" .FileSystem)" = "hfsplus" ]; then
	  log " ** Repairing Hfsplus filesystem" "display"
      fsck.hfsplus -f ${hard_drive}${partition_prefix}$(parse_json "$current_partition" .Number)
	  sleep 5
	fi
	
	if [ "$file_copy" = "True" ]; then
	  process_file_copy "$current_partition" "partition"
	fi
  done
}

function download_image()
{
  local current_object="$1"
  local file_name_prefix="$2"
  local destination
    
  if [ "$file_name_prefix" != "part" ]; then
    destination="/dev/mapper/$file_name_prefix"
	file_name_prefix=$(echo $file_name_prefix | sed 's/--/-/g')
  else
    destination=${hard_drive}${partition_prefix}$(parse_json "$current_object" .Number)
    file_name_prefix=part"$(parse_json "$current_object" .Number)"
  fi
  
  log " ** Starting Image Download For $destination ** " "display" 
  if [ -n "$computer_id" ]; then    
    null=$($curlAuth --data "computerId=$computer_id&partition=$destination" "${web}UpdateProgressPartition" $curlEnd)
  fi
  sleep 7
  echo
	
  if [ "$(parse_json "$current_object" .ImageType)" = "Block" ]; then
    if [ "$(parse_json "$current_object" .Compression)" = "gz" ]; then
      partCompAlg="gzip -c -d"
      partCompExt="gz"
    elif [ "$(parse_json "$current_object" .Compression)" = "lz4" ]; then
      partCompAlg="lz4 -d"
      partCompExt="lz4"
    elif [ "$(parse_json "$current_object" .Compression)" = "uncp" ]; then
      partCompAlg="none"
      partCompExt=""
    else
      error "Could Not Determine Compression Algorithm For Partition"
    fi
  		
  touch /tmp/clone.progress
			
  if [ "$multicast" = "true" ]; then
    if [ "$decompress_multicast_on_client" = "true" ]; then
	    log "cd_reporter $computer_id partclone $is_ondemand & udp-receiver --portbase $multicast_port --no-progress --mcast-rdv-address $server_ip $client_receiver_args | $partCompAlg | partclone.$(parse_json "$current_object" .PartcloneFileSystem) -B -r -o $destination"
      cd_reporter $computer_id partclone $is_ondemand & udp-receiver --portbase $multicast_port --no-progress --mcast-rdv-address $server_ip $client_receiver_args | $partCompAlg | partclone.$(parse_json "$current_object" .PartcloneFileSystem) -B -r -o $destination
	else #dcompress on server
      log "cd_reporter $computer_id partclone $is_ondemand & udp-receiver --portbase $multicast_port --no-progress --mcast-rdv-address $server_ip $client_receiver_args | partclone.$(parse_json "$current_object" .PartcloneFileSystem) -B -r -o $destination"
      cd_reporter $computer_id partclone $is_ondemand & udp-receiver --portbase $multicast_port --no-progress --mcast-rdv-address $server_ip $client_receiver_args | partclone.$(parse_json "$current_object" .PartcloneFileSystem) -B -r -o $destination
    fi
  else #unicast
    if [ "$partCompAlg" = "none" ]; then #no compression
	   cd_reporter $computer_id partclone $is_ondemand & partclone.$(parse_json "$current_object" .PartcloneFileSystem) -B -r -s $image_path/$file_name_prefix.$(parse_json "$current_object" .PartcloneFileSystem).uncp -o $destination
	   log "cd_reporter $computer_id partclone $is_ondemand & partclone.$(parse_json "$current_object" .PartcloneFileSystem) -B -r -s $image_path/$file_name_prefix.$(parse_json "$current_object" .PartcloneFileSystem).uncp -o $destination"
	else #compression in use
      log "cd_reporter $computer_id partclone $is_ondemand & $partCompAlg $image_path/$file_name_prefix.$(parse_json "$current_object" .PartcloneFileSystem).$partCompExt | partclone.$(parse_json "$current_object" .PartcloneFileSystem) -B -r -o $destination"
      cd_reporter $computer_id partclone $is_ondemand & $partCompAlg $image_path/$file_name_prefix.$(parse_json "$current_object" .PartcloneFileSystem).$partCompExt | partclone.$(parse_json "$current_object" .PartcloneFileSystem) -B -r -o $destination
	fi
  fi
			
  rm /tmp/clone.progress
  cat /var/log/partclone.log >> $CLIENT_LOG
  else # ImageType = File
    export WIMLIB_IMAGEX_USE_UTF8=1
    log " ** Creating $(parse_json "$current_object" .FileSystem) Filesystem On $destination ** "
    if [ "$(parse_json "$current_object" .FileSystem)" = "ntfs" ]; then
	  log "mkfs.$(parse_json "$current_object" .FileSystem) -f $destination"
	  mkfs.$(parse_json "$current_object" .FileSystem) -f $destination &>> $CLIENT_LOG
	elif [ "$(parse_json "$current_object" .FileSystem)" = "xfs" ]; then
	  log "mkfs.$(parse_json "$current_object" .FileSystem) -f $destination"
	  wim_arguments=" --unix-data"
	  mkfs.$(parse_json "$current_object" .FileSystem) -f $destination &>> $CLIENT_LOG
	  xfs_admin -U $(parse_json "$current_object" .Uuid) $destination &>> $CLIENT_LOG
	else #ext filesystems
	  log "mkfs.$(parse_json "$current_object" .FileSystem) -F $destination"
	  wim_arguments=" --unix-data"
	  mkfs.$(parse_json "$current_object" .FileSystem) -F $destination &>> $CLIENT_LOG
	  tune2fs $destination -U $(parse_json "$current_object" .Uuid) &>> $CLIENT_LOG
	fi
	
	
	if [ "$(parse_json "$current_object" .FileSystem)" != "ntfs" ]; then
	  mkdir /mnt/fs &> /dev/null
	  umount /mnt/fs &> /dev/null
	  mount $destination /mnt/fs 2>> $CLIENT_LOG
	  destination="/mnt/fs"
	fi
	
	if [ "$multicast" = "true" ]; then
	  log "cd_reporter $computer_id wimdown $is_ondemand & udp-receiver --portbase $multicast_port --no-progress --mcast-rdv-address $server_ip $client_receiver_args | wimapply - 1 $destination $wim_arguments"
	  cd_reporter $computer_id wimdown $is_ondemand & udp-receiver --portbase $multicast_port --no-progress --mcast-rdv-address $server_ip $client_receiver_args | wimapply - 1 $destination $wim_arguments 2>> $CLIENT_LOG | tee /tmp/wim.progress
	else
	  log "cd_reporter $computer_id wimdown $is_ondemand & wimapply $image_path/$file_name_prefix.$(parse_json "$current_object" .PartcloneFileSystem).wim 1 $destination $wim_arguments"
	  cd_reporter $computer_id wimdown $is_ondemand & wimapply $image_path/$file_name_prefix.$(parse_json "$current_object" .PartcloneFileSystem).wim 1 $destination $wim_arguments 2>> $CLIENT_LOG | tee /tmp/wim.progress
	fi
  fi 
}

function restore_mbr_gpt()
{
  local gpt_status
  local hybrid_status
  
  log " ** Restoring MBR / GPT On $hard_drive ** " "display"
  dd if=$image_path/table of=$hard_drive &>>$CLIENT_LOG				
		
  #Sometimes restoring results in damaged GPT.
  gpt_status=$(gdisk -l $hard_drive <<< "2" 2>>$CLIENT_LOG | grep 'GPT:' | awk '{$1=""; print $0}' | sed 's/^ //')
  if [ "$gpt_status" = "damaged" ]; then
    gdisk $hard_drive << eof >> $CLIENT_LOG
2
w
y
eof
  fi
	
  hybrid_status=$(gdisk -l $hard_drive <<< "q" 2>> $CLIENT_LOG| grep 'MBR:' | awk '{$1=""; print $0}' | sed 's/^ //')
  if [ "$hybrid_status" = "hybrid" ]; then
    gpt_is_hybrid="true"
  fi
	
  log " ...... Complete" "display"
  echo 
  partprobe &>/dev/null
  sleep 2
}

function update_grub()
{

	log " ** Checking If Grub Is Required ** "
	dd if=$hard_drive of=/tmp/grubcheck bs=512 count=1 2> /dev/null
	strings /tmp/grubcheck | grep -i "grub"
	if [ "$?" = "0" ]; then
		log " ...... Grub Is Required, Searching For Boot Files "
		if [ -n "$grubRoot" ]; then
			log " ...... Grub Root Overridden By User $grubRoot "
			grubHD=$(echo $grubRoot | cut -d"," -f1)
			grubHD="$grubHD)"
		else
			grub --batch <<eof>> /tmp/grubroot
find /grub/menu.lst
find /boot/grub/menu.lst
eof
			cat /tmp/grubroot >>$CLIENT_LOG
			grubRoot=$(cat /tmp/grubroot | grep -i "$hard_drive$current_hd_number")
			grubHD=$(echo $grubRoot | cut -d"," -f1)
			grubHD="$grubHD)"
		fi
			log "grubRoot: $grubRoot grubHD: $grubHD current_hd_number: $current_hd_number"
		
		if [ -n "$grubRoot" ]; then
			log " ...... Found Legacy Grub On $grubRoot "
			log " ...... Restoring Grub Legacy "
			grub --batch <<eof>> $CLIENT_LOG
root $grubRoot
setup $grubHD
eof
		else
			log " ...... Could Not Find Boot Files For Grub Legacy."
		fi
	else
		log " ...... Grub Is Not Required"
	fi
}


function create_partition_layout()
{
  local layout_created_successfully
  local layout_failed_counter
  local gpt_partition_count
  local mbr_partition_count
  local preexisting_volume_groups
  local preexisting_physical_volumes
  local new_volume_groups
  local new_logical_volumes
  local volume_group_uuid
  local logical_volume_uuid
  
  if [ "$(parse_json "$hd_schema" .IsValid)" = "true" ]; then
    log " ...... HD Meets The Minimum Sized Required"		
  elif [ "$(parse_json "$hd_schema" .IsValid)" = "false" ]; then
    log " ...... $(parse_json "$hd_schema" .Message)" "display"
    sleep 10
    continue		
  elif [ "$(parse_json "$hd_schema" .IsValid)" = "original" ]; then
    log " ...... HD Matches Original Size Of Image, Dynamic Partition Layout Will Not Be Used"
  else
    error "Unknown Error Occurred While Determining Minimum HD Size Required.  Check The Exception Log"
  fi
	
  erase_mbr_gpt
  restore_mbr_gpt
  
  get_partitions_according_to_mbr_gpt
  partition_counter=0
	for partition in $mbr_gpt_partitions; do
      partition_counter=$(( $partition_counter + 1 ))
      partition_number=`echo $partition | awk -F $hard_drive ' {print $2}' | sed 's/[^0-9]//g'`
      partition_prefix=`echo $partition | awk -F $hard_drive ' {print $2}' | sed 's/[0-9]*//g'`
	  break
	done
	
  if [ "$partition_method" = "script" ]; then # create partitions from image profile script
     log " ** Creating Partition Table On $hard_drive From Custom Script ** " "display"
    $curlAuth --data "profileId=$profile_id" "${web}GetCustomPartitionScript" $curlEnd | dos2unix > /tmp/newPartLayout
	cat /tmp/newPartLayout >> $CLIENT_LOG
    bash /tmp/newPartLayout
    partprobe &>/dev/null
  elif [ "$partition_method" = "original" ]; then # create partitions from original mbr / gpt
     log " ** Creating Partition Table On $hard_drive From Original MBR / GPT ** " "display"
	 #This doesn't really do anything, partition table was already restored, it's just here so the next elif does run
  elif [ "$(parse_json "$hd_schema" .IsValid)" = "true" ] || [ "$force_dynamic_partitions" = "true" ]; then # create partitions dynamically from image profile settings
    log " ** Creating Partition Table On $hard_drive ** " "display"
    $curlAuth --data "imageProfileId=$profile_id&hdToGet=$image_hd_to_use&newHDSize=$drive_size_bytes&clientHD=$hard_drive&taskType=deploy&partitionPrefix=$partition_prefix&lbs=$lbs" "${web}GetPartLayout" $curlEnd | dos2unix > /tmp/newPartLayout
	if [ "$(cat /tmp/newPartLayout)" = "failed" ]; then
	  error "Could Not Dynamically Create Partition Layout"
	fi
		
    layout_failed_counter=0
    if [ "$(parse_json "$hd_schema" .PartitionType)" = "gpt" ]; then
      while [ "$layout_created_successfully" != "true" ]; do		
        delete_all_partitions $hard_drive
		log " ** Partition Creation Script ** "
        cat /tmp/newPartLayout >> $CLIENT_LOG
        bash /tmp/newPartLayout
        partprobe &>/dev/null
        gpt_partition_count=$(gdisk -l $hard_drive 2> /dev/null| awk '/^ / {print $1}' | grep -vi mbr | grep -vi gpt | grep -vi bsd | grep -vi apm -c)
        if [ "$gpt_partition_count" = "$(parse_json "$hd_schema" .PhysicalPartitionCount)" ]; then
          layout_created_successfully="true"
          log " ...... Success" "display"
        else
          layout_failed_counter=$(( $layout_failed_counter + 1 ))
          log " ...... Could Not Create Partition Layout.  Retrying Attempt $layout_failed_counter"
          if [ "$layout_failed_counter" -gt "10" ]; then
            error "Could Not Create Partition Layout"
          fi
        fi
      done
    else #partitiontype is mbr
      delete_all_partitions $hard_drive
	  log " ** Partition Creation Script ** "
      cat /tmp/newPartLayout >> $CLIENT_LOG
      bash /tmp/newPartLayout
      partprobe &>/dev/null
      mbr_partition_count=$(fdisk -l 2>/dev/null | grep $hard_drive | grep -v ${hard_drive}: -c)
      if [ "$mbr_partition_count" != "$(parse_json "$hd_schema" .PhysicalPartitionCount)" ]; then
        error "Could Not Create Partition Layout"
      fi
    fi
  fi #if neither conditions matched above, partitions were created when the mbr /gpt was restored.
	
  log " ** New Partition Table Is ** "
  if [ "$(parse_json "$hd_schema" .PartitionType)" = "gpt" ]; then
    gdisk -l $hard_drive &>>$CLIENT_LOG
  else
    fdisk -l &>>$CLIENT_LOG
  fi
	
  if [ "$gpt_is_hybrid" = "true" ]; then
    create_hybrid_gpt
  fi
	
  if [ "$(parse_json "$hd_schema" .UsesLvm)" = "true" ]; then
    if [ "$(parse_json "$hd_schema" .IsValid)" = "original" ] && [ "$force_dynamic_partitions" != "true" ]; then
      log "Creating Original LVM"
      $curlAuth --data "profileId=$profile_id&clientHd=$hard_drive&hdToGet=$image_hd_to_use&partitionPrefix=$partition_prefix" "${web}GetOriginalLvm" $curlEnd | dos2unix > /tmp/lvmcommands
      cat /tmp/lvmcommands >> $CLIENT_LOG
    fi
	
    if [ -s "/tmp/lvmcommands" ]; then
      dmsetup remove_all
      preexisting_volume_groups=$(vgs --noheadings | awk '/^ / {print $1}')
      for vg in $preexisting_volume_groups; do
        vgremove $vg -fy
      done
	
      preexisting_physical_volumes=$(pvs --noheadings | grep $hard_drive | awk '/^ / {print $1}')
      for pv in $preexisting_physical_volumes; do
        pvremove $pv -fy
      done
	
      bash /tmp/lvmcommands &>>$CLIENT_LOG
      vgscan
		
      new_volume_groups=$(vgs --noheadings | awk '/^ / {print $1}')
      for vg in $new_volume_groups; do
        new_logical_volumes=$(lvs | grep "$vg" | awk '/^ / {print $1}')
        volume_group_uuid=$(vgs -v  2>/dev/null | grep "$vg" | awk '/^ / {print $9}')
        sed -i "s/$volume_group_uuid/$(cat /tmp/vg-$vg)/g" /tmp/lvm-$vg 
        for logical_volume in $new_logical_volumes; do		
          logical_volume_uuid=$(lvs -v 2>/dev/null | grep "$vg" | grep "$logical_volume" | awk '/^ / {print $10}')
          sed -i "s/$logical_volume_uuid/$(cat /tmp/$vg-$logical_volume)/g" /tmp/lvm-$vg 
        done
        vgcfgrestore $vg -f /tmp/lvm-$vg
      done			
    else
      return 0
    fi
  fi
}

function create_hybrid_gpt()
{
  #Fix Me. Very generic way of creating hybrid.  May not work in many situations.
  gdisk $hard_drive << eof >> $CLIENT_LOG
r
h
2 3 4 5 6 7 8 9 10
y

n

n

n

n

w
y
eof

  fdisk $hard_drive << eof >> $CLIENT_LOG
x
M
r
a
$(parse_json "$hd_schema" .BootPartition)
w
q
eof
}

function get_partitions_according_to_mbr_gpt()
{
  mbr_gpt_partitions=""
  mbr_gpt_partitions=$(lsblk -ipno KNAME | grep "$hard_drive" | grep -vw "$hard_drive" | grep -v "boot" 2>> $CLIENT_LOG)  
}

function update_efi_nvram()
{
  log "Updating NVRAM"
  gdisk -l $hard_drive | grep EF00
  if [ "$?" != "0" ]; then
    log "No EFI System Partition Found."
	gdisk -l $hard_drive >> $CLIENT_LOG
	return 1;
  fi
  
  mount -t efivarfs none /sys/firmware/efi/efivars &>>$CLIENT_LOG
  
  log "Existing NVRAM"
  efibootmgr -v &>> $CLIENT_LOG
  if [ "$?" != "0"]; then
    log "EFI Variables Are Not Available"
	return 1
  fi
  
  boot_entries_to_delete=$(efibootmgr -v | grep "File(" | cut -d "*" -f1 | sed 's/Boot//g')

  local array_index=-1
  while [  "$(( $array_index + 1 ))" -lt "$(parse_json "$hd_schema" .PhysicalPartitionCount)" ]; do
    array_index=$(( $array_index + 1))
    clear_and_move_down
    current_partition="$(parse_json "$hd_schema" .PhysicalPartitions[$array_index])"
	existing_bootloader=$(efibootmgr -v | grep -i "$(parse_json "$current_partition" .Guid)" | grep -o "File(.*)" | cut -d "(" -f2 | cut -d ")" -f1 | uniq)
	boot_number=$(efibootmgr -v | grep -i "$(parse_json "$current_partition" .Guid)" | cut -d "*" -f1 | sed 's/Boot//g')
	log "$(parse_json "$current_partition" .Number) $existing_bootloader $boot_number"
	if [ -n "$existing_bootloader" ] && [ "$existing_bootloader" = "$(parse_json "$current_partition" .EfiBootLoader)" ]; then
	  log "NVRAM Entry Already Exists"
	  #This partition already has a matching entry in the nvram
	  #Don't delete it.
	  boot_entries_to_delete=$(echo $boot_entries_to_delete | sed "s/$boot_number//g")
	elif [ -n "$existing_bootloader" ]; then
	  log "Updating NVRAM Entry"
	  #Partition has entry in nvram but bootloader doesn't match
	  #Update it and don't delete
	  efibootmgr -B -b $boot_number 2>>$CLIENT_LOG
	  efibootmgr -c -d $hard_drive -p "$(parse_json "$current_partition" .Number)" -L "$(parse_json "$current_partition" .EfiBootLoader)" -l "$(parse_json "$current_partition" .EfiBootLoader)" 2>>$CLIENT_LOG
	  boot_entries_to_delete=$(echo $boot_entries_to_delete | sed "s/$boot_number//g")
	else
	  #Partition Does not exist in the nvram
	  #Check if it should
	  if [ -n "$(parse_json "$current_partition" .EfiBootLoader)" ] && [ "$(parse_json "$current_partition" .EfiBootLoader)" != "null" ]; then
	     log "Creating New NVRAM Entry"
	    #Entry needs added
	    efibootmgr -c -d $hard_drive -p "$(parse_json "$current_partition" .Number)" -L "$(parse_json "$current_partition" .EfiBootLoader)" -l "$(parse_json "$current_partition" .EfiBootLoader)" 2>>$CLIENT_LOG
	  fi
	fi
  done
  
  #Delete remaining boot entries
   for efi_boot in $boot_entries_to_delete; do
    efibootmgr -B -b $efi_boot 2>>$CLIENT_LOG
  done	
  
  log "Updated NVRAM"
  efibootmgr -v &>> $CLIENT_LOG
  
}

function update_bcd()
{
  #Fix Me.  Function is run once against each hard drive.  If hard drive is dual boot of multiple version of Windows, this will fail.
  local windows_partition
  local windows_partition_offset
  local bcd_partition
  local original_bcd
  local updated_bcd
  
  if [ "$fix_bcd" != "true" ]; then
    log "BCD Update Has Been Skipped Via Image Profile"
    return 0
  fi

  local array_index=-1
  while [  "$(( $array_index + 1 ))" -lt "$(parse_json "$hd_schema" .PhysicalPartitionCount)" ]; do
    array_index=$(( $array_index + 1))
    clear_and_move_down
    current_partition="$(parse_json "$hd_schema" .PhysicalPartitions[$array_index])"
    if [ "$(parse_json "$current_partition" .FileSystem)" != "ntfs" ]; then
      continue
    fi

	umount /mnt/ntfs
    log " ** Updating BCD ** " "display"
    mkdir /mnt/ntfs
    ntfs-3g -o force,rw,remove_hiberfile ${hard_drive}${partition_prefix}$(parse_json "$current_partition" .Number) /mnt/ntfs 2>> $CLIENT_LOG
    if [ -f "/mnt/ntfs/Windows/System32/winload.exe" ] || [ -f "/mnt/ntfs/Windows/system32/winload.exe" ]; then
      log " ...... Found Windows Partition On ${hard_drive}${partition_prefix}$(parse_json "$current_partition" .Number)" "display"
      windows_partition=${hard_drive}${partition_prefix}$(parse_json "$current_partition" .Number)	
      windows_partition_offset=$(parted -s $hard_drive unit b print all | grep " $(parse_json "$current_partition" .Number) " -m 1 | awk -F' ' '{print $2}' | sed 's/B//g')			
    fi
		
    if [ -f "/mnt/ntfs/Boot/BCD" ]; then
      log " ...... Found BCD Partition On${hard_drive}${partition_prefix}$(parse_json "$current_partition" .Number)" "display"
      bcd_partition=${hard_drive}${partition_prefix}$(parse_json "$current_partition" .Number)
      reged -x /mnt/ntfs/Boot/BCD . Objects /tmp/regbcd >> /dev/null
      original_bcd=$(cat /tmp/regbcd)
    fi
    umount /mnt/ntfs
  done
  
   if [ -n "$windows_partition" ] && [ -n "$bcd_partition" ]; then
    updated_bcd=$($curlAuth -F bcd="$(echo -n "$original_bcd" | base64)" -F offsetBytes="$(echo -n "$windows_partition_offset" | base64)" "${web}UpdateBcd" $curlEnd)
    echo $updated_bcd | base64 -d >>/tmp/updatedbcd
    log " ** Updated BCD Is ** "
    cat /tmp/updatedbcd >> $CLIENT_LOG	
    ntfs-3g -o force,rw,remove_hiberfile $bcd_partition /mnt/ntfs 2>> $CLIENT_LOG
    reged -I -C /mnt/ntfs/Boot/BCD . /tmp/updatedbcd >> $CLIENT_LOG
    umount /mnt/ntfs
    log " ...... Success" "display"
  else
    log " ...... Could Not Verify Windows Partition Or BCD Partition.  BCD Has Not Been Changed" "display"
    log " ...... windows_partition: $windows_partition bcd_partition: $bcd_partition" 
  fi	
  echo
}

function fix_ntfs_boot()
{
  if [ "$fix_bootloader" != "true" ]; then
    log "Bootloader fix Has Been Skipped Via Image Profile"
    return 0
  fi
  local partition="$1"
  log " ** Fixing NTFS Bootloader ** " "display"
  partclone.ntfsfixboot -p $partition >> $CLIENT_LOG
  partclone.ntfsfixboot -w $partition >> $CLIENT_LOG
		
}

function erase_mbr_gpt()
{
  log " ** Clearing MBR / GPT ** "
  sgdisk -Z $hard_drive &>>$CLIENT_LOG
  dd if=/dev/zero of=$hard_drive bs=512 count=2047 &>>$CLIENT_LOG
  partprobe &> /dev/null
}

function delete_all_partitions()
{
  local partition_count
  local delete_counter
  #Delete all partitions but keep boot record intact
  log " ** Deleting Existing Partitions ** "
  if [ "$(parse_json "$hd_schema" .PartitionType)" = "gpt" ]; then
    partition_count=$(gdisk -l $1 2> /dev/null| awk '/^ / {print $1}' | grep -vi mbr | grep -vi gpt | grep -vi bsd | grep -vi apm -c)
    delete_counter=0
    while [ "$partition_count" -gt "0" ]; do
      delete_counter=$(( $delete_counter + 1 ))
      echo "gdisk $1 &>/dev/null <<GDISK" > /tmp/partition_delete
      for part_num in $(gdisk -l $1 2> /dev/null | awk '/^ / {print $1}' | grep -vi mbr | grep -vi gpt | grep -vi bsd | grep -vi apm); do			
        echo d >> /tmp/partition_delete
        echo "$part_num" >> /tmp/partition_delete
      done
			
      echo w >> /tmp/partition_delete
      echo y >> /tmp/partition_delete
      echo y >> /tmp/partition_delete
      echo q >> /tmp/partition_delete
      echo GDISK >> /tmp/partition_delete
      cat /tmp/partition_delete >> $CLIENT_LOG
      bash /tmp/partition_delete
			
      gdisk $1 &>/dev/null <<GDISK
d
$part_num
w
y
y
q
GDISK
			
      partition_count=$(gdisk -l $1 2> /dev/null | awk '/^ / {print $1}' | grep -vi mbr | grep -vi gpt | grep -vi bsd | grep -vi apm -c)
      if [ "$delete_counter" -gt "1000" ]; then
        log " ...... Partitions Still Exist"
        gdisk -l $1 &>>$CLIENT_LOG
        error "Could Not Delete GPT Partitions"
      fi
    done		
  else #mbr
    partition_count=$(fdisk -l 2>/dev/null | grep $hard_drive | grep -v ${hard_drive}: -c)
    delete_counter=0
    while [ "$partition_count" -gt "0" ]; do
      delete_counter=$(( $delete_counter + 1 ))
      fdisk $1 &>/dev/null <<FDISK
d


w
FDISK
      partition_count=$(fdisk -l 2>/dev/null | grep $hard_drive | grep -v ${hard_drive}: -c)
      if [ "$delete_counter" -gt "1000" ]; then
        log " ...... Partitions Still Exist"
        fdisk -l &>>$CLIENT_LOG
        error "Could Not Delete MBR Partitions"			
      fi
    done
  fi
}

function change_computer_name()
{  
  local partition="$1"
  log " ** Changing Computer Name On $partition ** " "display"
  mkdir /mnt/ntfs		
  ntfs-3g -o force,rw,remove_hiberfile $partition /mnt/ntfs 2>> $CLIENT_LOG
  if [ "$?" != "0" ]; then
    log "Could Not Mount NTFS To Change Computer Name"
	return 1
  fi
  
  if [ -f "/mnt/ntfs/Windows/Panther/unattend.xml" ]; then
    log " ...... Found Answer File At /Windows/Panther/unattend.xml, Changing Computer Name" "display"
    perl -0777 -i -pe "s/(\<ComputerName\>).*(\<\/ComputerName\>)/\${1}$computer_name\${2}/si" /mnt/ntfs/Windows/Panther/unattend.xml 
  elif [ -f "/mnt/ntfs/Windows/System32/sysprep/Panther/unattend.xml" ]; then
    log " ...... Found Answer File At /Windows/System32/sysprep/Panther/unattend.xml, Changing Computer Name" "display"
    perl -0777 -i -pe "s/(\<ComputerName\>).*(\<\/ComputerName\>)/\${1}$computer_name\${2}/si" /mnt/ntfs/Windows/System32/sysprep/Panther/unattend.xml
  elif [ -f "/mnt/ntfs/Sysprep/sysprep.inf" ]; then
    log " ...... Found Answer File, Changing Host Name" "display"
    sed -i "s/^\s*ComputerName=.*$/ComputerName=$computer_name\r/I" /mnt/ntfs/Sysprep/sysprep.inf
  else
    log " ...... Could Not Find Answer File, Attempting Registry Change" "display"
	#Editing the registry is case sensitive, these are all the variations I have found so far.
    update_registry_key "/mnt/ntfs/Windows/System32/config/SYSTEM" "\ControlSet001\Services\Tcpip\Parameters\NV Hostname" "$computer_name"
    update_registry_key "/mnt/ntfs/Windows/System32/config/SYSTEM" "\ControlSet001\Control\ComputerName\ComputerName\ComputerName" "$computer_name"				
    update_registry_key "/mnt/ntfs/Windows/System32/config/SYSTEM" "\ControlSet001\Services\Tcpip\Parameters\Hostname" "$computer_name"
    update_registry_key "/mnt/ntfs/Windows/System32/config/SYSTEM" "\ControlSet001\Services\Tcpip\Parameters\HostName" "$computer_name"				
    update_registry_key "/mnt/ntfs/Windows/System32/config/SYSTEM" "\ControlSet001\Services\Tcpip\Parameters\NV HostName" "$computer_name"
    update_registry_key "/mnt/ntfs/Windows/System32/config/SYSTEM" "\ControlSet001\services\Tcpip\Parameters\NV Hostname" "$computer_name"					
    update_registry_key "/mnt/ntfs/WINDOWS/system32/config/system" "\ControlSet001\Services\Tcpip\Parameters\NV Hostname" "$computer_name"
    update_registry_key "/mnt/ntfs/WINDOWS/system32/config/system" "\ControlSet001\Control\ComputerName\ComputerName\ComputerName" "$computer_name"
  fi
  umount /mnt/ntfs	
}




function main()
{
  log_boot_args

  if [ "$is_ondemand" = "true" ]; then
    log " ** Using On Demand Mode ** "
	for arg in "$ondemand_arguments"; do case "$arg" in *=*) eval "$arg"; log "$arg"; esac; done
  elif [ "$task" = "clobber" ]; then
    log " ** Using Clobber Mode ** "
	clobber_args=$($curlAuth --data "mac=$mac&objectId=$imageProfileId&task=push" "${web}GetOnDemandArguments" $curlEnd)
    for arg in "$clobber_args"; do case "$arg" in *=*) eval "$arg"; log "$arg"; esac; done
	if [ "$computer_name" = "" ] || [ "$computer_name" = "null" ]; then
	  if [ "$name_prompt" = "true" ]; then
		echo "This Computer Was Not Found In The Database, Enter A Name For It Now:"
		echo "Leave Blank To Skip Computer Renaming"
		echo
		read computer_name
		echo
		if [ -n "$computer_name" ]; then
		  computer_name=$computer_name
		fi
	  fi
	fi
  else
    checkin
  fi
  
  if [ "$is_ondemand" != "true" ]; then
  if [ "$task" = "push" ] || [ "$task" = "permanent_push" ]; then	
	if [ "$multicast" = "true" ]; then
	  $curlAuth --data "computerId=$computer_id" "${web}UpdateStatusInProgress" $curlEnd
	else
	  log " ** Checking Current Queue ** " "display"	
      while true; do
	    queue_status=$($curlAuth --data "computerId=$computer_id" "${web}CheckQueue" $curlEnd)
		if [ "$(parse_json "$queue_status" .Result)" = "true" ]; then
		  break
		else
		  echo "** Queue Is Full, Waiting For Open Slot ** "
		  echo " ...... Current Position $(parse_json "$queue_status" .Position)"
		  sleep 5
		fi
      done
	    log " ...... Complete" "display"
		echo
	fi	  		
  fi
  fi
   
  sleep 2

  mount_smb

  process_hard_drives
	
  checkout
}

is_ondemand="$1"
ondemand_arguments="$2"
main "$@"

