#!/bin/bash

. /usr/local/bin/osx_global_functions

computer_id=$1


  while [ -f "/tmp/osx.progress" ]; do
    post=$(tail -n 1 /tmp/osx.progress)
    result=$($curlAuth --data "computerId=$computer_id&progress=$post&progressType=wim" "${web}UpdateProgress" $curlEnd)        
	echo $post
    sleep 2
  done	


